-- 코드를 입력하세요
SELECT DISTINCT C.CART_ID
FROM (
    SELECT CART_ID,NAME
    FROM CART_PRODUCTS C
    WHERE C.NAME='Yogurt'
)as CY,CART_PRODUCTS C
WHERE CY.CART_ID=C.CART_ID AND C.NAME='Milk'
ORDER BY CART_ID ASC